name: drawReco
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - flask=2.0.1
  - pytorch=1.9.0
  - torchvision=0.10.0
  - numpy=1.21.0
  - pillow=8.3.1
  - werkzeug=2.0.1